package com.Polarice3.goety_cataclysm.client.render.model;

import com.Polarice3.goety_cataclysm.common.entities.ally.golem.CoralGolemServant;
import com.github.L_Ender.lionfishapi.client.model.Animations.ModelAnimator;
import com.github.L_Ender.lionfishapi.client.model.tools.AdvancedEntityModel;
import com.github.L_Ender.lionfishapi.client.model.tools.AdvancedModelBox;
import com.github.L_Ender.lionfishapi.client.model.tools.BasicModelPart;
import com.google.common.collect.ImmutableList;
import net.minecraft.client.Minecraft;

public class CoralGolemServantModel extends AdvancedEntityModel<CoralGolemServant> {
    private final AdvancedModelBox root;
    private final AdvancedModelBox lower_body;
    private final AdvancedModelBox upper_body;
    private final AdvancedModelBox helmet;
    private final AdvancedModelBox chest;
    private final AdvancedModelBox table_coral;
    private final AdvancedModelBox blue_table_coral;
    private final AdvancedModelBox red_table_coral;
    private final AdvancedModelBox right_arm;
    private final AdvancedModelBox right_fist;
    private final AdvancedModelBox right_coral;
    private final AdvancedModelBox left_arm;
    private final AdvancedModelBox left_fist;
    private final AdvancedModelBox left_coral;
    private final AdvancedModelBox coral_shoulder;
    private final AdvancedModelBox head;
    private final AdvancedModelBox right_leg;
    private final AdvancedModelBox left_leg;
    private ModelAnimator animator;

    public CoralGolemServantModel() {
        this.texWidth = 128;
        this.texHeight = 128;
        this.root = new AdvancedModelBox(this);
        this.root.setRotationPoint(0.0F, 24.0F, 0.0F);
        this.lower_body = new AdvancedModelBox(this);
        this.lower_body.setRotationPoint(0.0F, -6.3F, -1.8F);
        this.root.addChild(this.lower_body);
        this.setRotationAngle(this.lower_body, 0.1745F, 0.0F, 0.0F);
        this.lower_body.setTextureOffset(0, 21).addBox(-6.0F, -8.0F, -4.0F, 12.0F, 8.0F, 8.0F, 0.0F, false);
        this.upper_body = new AdvancedModelBox(this);
        this.upper_body.setRotationPoint(0.0F, -6.2F, 2.8F);
        this.lower_body.addChild(this.upper_body);
        this.setRotationAngle(this.upper_body, 0.6981F, 0.0F, 0.0F);
        this.helmet = new AdvancedModelBox(this);
        this.helmet.setRotationPoint(-0.5F, -11.0F, -6.5F);
        this.upper_body.addChild(this.helmet);
        this.setRotationAngle(this.helmet, -0.6109F, 0.0F, 0.0F);
        this.helmet.setTextureOffset(54, 59).addBox(-3.5F, -7.5F, -3.5F, 8.0F, 8.0F, 8.0F, 0.0F, false);
        this.helmet.setTextureOffset(89, 31).addBox(4.5F, -6.5F, -2.5F, 1.0F, 6.0F, 6.0F, 0.0F, false);
        this.helmet.setTextureOffset(87, 66).addBox(-4.5F, -6.5F, -2.5F, 1.0F, 6.0F, 6.0F, 0.0F, false);
        this.helmet.setTextureOffset(35, 32).addBox(-6.5F, -0.5F, -2.5F, 14.0F, 7.0F, 6.0F, 0.0F, false);
        this.helmet.setTextureOffset(21, 78).addBox(5.5F, -1.5F, -3.5F, 2.0F, 5.0F, 8.0F, 0.0F, false);
        this.helmet.setTextureOffset(65, 76).addBox(-6.5F, -1.5F, -3.5F, 2.0F, 5.0F, 8.0F, 0.0F, false);
        this.helmet.setTextureOffset(47, 0).addBox(-1.5F, -8.5F, -1.5F, 4.0F, 1.0F, 4.0F, 0.0F, false);
        this.helmet.setTextureOffset(86, 0).addBox(0.5F, -14.25F, 0.5F, 9.0F, 9.0F, 0.0F, 0.0F, false);
        this.chest = new AdvancedModelBox(this);
        this.chest.setRotationPoint(0.0F, -3.5F, -3.0F);
        this.upper_body.addChild(this.chest);
        this.chest.setTextureOffset(0, 0).addBox(-9.0F, -6.5F, -4.75F, 18.0F, 10.0F, 10.0F, 0.0F, false);
        this.table_coral = new AdvancedModelBox(this);
        this.table_coral.setRotationPoint(8.0F, -2.0F, 5.0F);
        this.chest.addChild(this.table_coral);
        this.table_coral.setTextureOffset(46, 24).addBox(-1.0F, -2.0F, -2.0F, 4.0F, 2.0F, 4.0F, 0.0F, false);
        this.table_coral.setTextureOffset(59, 23).addBox(-1.0F, 1.0F, -2.0F, 3.0F, 1.0F, 3.0F, 0.0F, false);
        this.blue_table_coral = new AdvancedModelBox(this);
        this.blue_table_coral.setRotationPoint(-5.0F, -3.0F, 0.0F);
        this.table_coral.addChild(this.blue_table_coral);
        this.blue_table_coral.setTextureOffset(44, 76).addBox(0.0F, -5.5F, -1.75F, 0.0F, 10.0F, 10.0F, 0.0F, false);
        this.red_table_coral = new AdvancedModelBox(this);
        this.red_table_coral.setRotationPoint(-3.0F, -3.0F, 0.0F);
        this.table_coral.addChild(this.red_table_coral);
        this.red_table_coral.setTextureOffset(78, 82).addBox(0.0F, -4.5F, 0.25F, 0.0F, 8.0F, 8.0F, 0.0F, false);
        this.right_arm = new AdvancedModelBox(this);
        this.right_arm.setRotationPoint(-9.0F, -6.7F, -1.7F);
        this.chest.addChild(this.right_arm);
        this.setRotationAngle(this.right_arm, -0.6109F, 0.0F, 0.0F);
        this.right_arm.setTextureOffset(57, 0).addBox(-6.0F, -4.0F, -4.0F, 6.0F, 14.0F, 8.0F, 0.0F, false);
        this.right_arm.setTextureOffset(29, 46).addBox(-7.1F, 2.0F, -5.0F, 9.0F, 2.0F, 10.0F, 0.0F, false);
        this.right_arm.setTextureOffset(76, 13).addBox(-0.1F, -5.0F, -5.0F, 2.0F, 7.0F, 10.0F, 0.0F, false);
        this.right_fist = new AdvancedModelBox(this);
        this.right_fist.setRotationPoint(-3.0F, 6.6F, -2.0F);
        this.right_arm.addChild(this.right_fist);
        this.setRotationAngle(this.right_fist, -0.2618F, 0.0F, 0.0F);
        this.right_fist.setTextureOffset(21, 59).addBox(-4.0F, 0.0F, -4.0F, 8.0F, 9.0F, 8.0F, 0.0F, false);
        this.right_coral = new AdvancedModelBox(this);
        this.right_coral.setRotationPoint(-4.0F, 6.0F, 0.0F);
        this.right_fist.addChild(this.right_coral);
        this.right_coral.setTextureOffset(0, 86).addBox(-8.0F, -8.0F, 0.0F, 8.0F, 11.0F, 0.0F, 0.0F, false);
        this.left_arm = new AdvancedModelBox(this);
        this.left_arm.setRotationPoint(9.0F, -6.7F, -1.7F);
        this.chest.addChild(this.left_arm);
        this.setRotationAngle(this.left_arm, -0.6109F, 0.0F, 0.0F);
        this.left_arm.setTextureOffset(0, 0).addBox(-1.0F, 8.0F, -4.0F, 2.0F, 2.0F, 2.0F, 0.0F, true);
        this.left_arm.setTextureOffset(0, 38).addBox(0.0F, -4.0F, -4.0F, 6.0F, 14.0F, 8.0F, 0.0F, false);
        this.left_arm.setTextureOffset(33, 21).addBox(3.0F, -1.0F, -5.0F, 4.0F, 2.0F, 4.0F, 0.0F, false);
        this.left_arm.setTextureOffset(21, 38).addBox(5.0F, 2.0F, -5.0F, 3.0F, 1.0F, 3.0F, 0.0F, false);
        this.left_fist = new AdvancedModelBox(this);
        this.left_fist.setRotationPoint(3.0F, 6.6F, -2.0F);
        this.left_arm.addChild(this.left_fist);
        this.setRotationAngle(this.left_fist, -0.2618F, 0.0F, 0.0F);
        this.left_fist.setTextureOffset(21, 59).addBox(-4.0F, 0.0F, -4.0F, 8.0F, 9.0F, 8.0F, 0.0F, true);
        this.left_coral = new AdvancedModelBox(this);
        this.left_coral.setRotationPoint(4.0F, 6.0F, 0.0F);
        this.left_fist.addChild(this.left_coral);
        this.left_coral.setTextureOffset(0, 86).addBox(0.0F, -8.0F, 0.0F, 8.0F, 11.0F, 0.0F, 0.0F, true);
        this.coral_shoulder = new AdvancedModelBox(this);
        this.coral_shoulder.setRotationPoint(-1.0F, -1.0F, 0.0F);
        this.left_arm.addChild(this.coral_shoulder);
        this.coral_shoulder.setTextureOffset(79, 55).addBox(4.0F, -10.0F, -1.0F, 9.0F, 10.0F, 0.0F, 0.0F, false);
        this.head = new AdvancedModelBox(this);
        this.head.setRotationPoint(0.0F, 2.5F, 1.0F);
        this.upper_body.addChild(this.head);
        this.right_leg = new AdvancedModelBox(this);
        this.right_leg.setRotationPoint(-6.0F, -8.0F, 0.0F);
        this.root.addChild(this.right_leg);
        this.right_leg.setTextureOffset(0, 69).addBox(-3.0F, 0.0F, -4.0F, 6.0F, 8.0F, 8.0F, 0.0F, false);
        this.left_leg = new AdvancedModelBox(this);
        this.left_leg.setRotationPoint(6.0F, -8.0F, 0.0F);
        this.root.addChild(this.left_leg);
        this.left_leg.setTextureOffset(68, 38).addBox(-3.0F, 0.0F, -4.0F, 6.0F, 8.0F, 8.0F, 0.0F, false);
        this.animator = ModelAnimator.create();
        this.updateDefaultPose();
    }

    public void animate(CoralGolemServant entity, float f, float f1, float f2, float f3, float f4) {
        this.resetToDefaultPose();
        this.animator.update(entity);
        this.animator.setAnimation(CoralGolemServant.CORAL_GOLEM_LEAP);
        this.animator.setStaticKeyframe(5);
        this.animator.startKeyframe(15);
        this.animator.move(this.lower_body, 0.0F, 2.0F, 0.0F);
        this.animator.rotate(this.upper_body, (float)Math.toRadians(7.5), 0.0F, 0.0F);
        this.animator.rotate(this.helmet, (float)Math.toRadians(-12.5), 0.0F, 0.0F);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-65.0), (float)Math.toRadians(5.0), (float)Math.toRadians(2.5));
        this.animator.rotate(this.right_fist, (float)Math.toRadians(12.5), 0.0F, 0.0F);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-65.0), (float)Math.toRadians(-5.0), (float)Math.toRadians(-2.0));
        this.animator.rotate(this.left_fist, (float)Math.toRadians(15.0), 0.0F, 0.0F);
        this.animator.move(this.right_leg, 0.0F, 0.0F, 3.0F);
        this.animator.move(this.left_leg, 0.0F, 0.0F, -3.0F);
        this.animator.endKeyframe();
        this.animator.startKeyframe(10);
        this.animator.rotate(this.lower_body, (float)Math.toRadians(-15.0), 0.0F, 0.0F);
        this.animator.rotate(this.upper_body, (float)Math.toRadians(-52.5), 0.0F, 0.0F);
        this.animator.rotate(this.helmet, (float)Math.toRadians(45.0), 0.0F, 0.0F);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-187.5), (float)Math.toRadians(-2.5), (float)Math.toRadians(-5.0));
        this.animator.rotate(this.right_fist, (float)Math.toRadians(12.5), 0.0F, 0.0F);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-185.0), (float)Math.toRadians(5.0), (float)Math.toRadians(5.0));
        this.animator.rotate(this.left_fist, (float)Math.toRadians(15.0), 0.0F, 0.0F);
        this.animator.move(this.right_leg, 0.0F, 0.0F, 1.0F);
        this.animator.move(this.left_leg, 0.0F, -2.0F, -5.0F);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(60);
        this.animator.resetKeyframe(10);
        this.animator.setAnimation(CoralGolemServant.CORAL_GOLEM_SMASH);
        this.animator.startKeyframe(0);
        this.animator.rotate(this.lower_body, (float)Math.toRadians(-15.0), 0.0F, 0.0F);
        this.animator.rotate(this.upper_body, (float)Math.toRadians(-52.5), 0.0F, 0.0F);
        this.animator.rotate(this.helmet, (float)Math.toRadians(45.0), 0.0F, 0.0F);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-187.5), (float)Math.toRadians(-2.5), (float)Math.toRadians(-5.0));
        this.animator.rotate(this.right_fist, (float)Math.toRadians(12.5), 0.0F, 0.0F);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-185.0), (float)Math.toRadians(5.0), (float)Math.toRadians(5.0));
        this.animator.rotate(this.left_fist, (float)Math.toRadians(15.0), 0.0F, 0.0F);
        this.animator.move(this.right_leg, 0.0F, 0.0F, 1.0F);
        this.animator.move(this.left_leg, 0.0F, -2.0F, -5.0F);
        this.animator.endKeyframe();
        this.animator.startKeyframe(3);
        this.animator.rotate(this.lower_body, (float)Math.toRadians(7.5), 0.0F, 0.0F);
        this.animator.rotate(this.helmet, (float)Math.toRadians(27.5), 0.0F, 0.0F);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-55.0), (float)Math.toRadians(-7.5), 0.0F);
        this.animator.rotate(this.right_fist, (float)Math.toRadians(12.5), 0.0F, 0.0F);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-55.0), 0.0F, (float)Math.toRadians(7.5));
        this.animator.rotate(this.left_fist, (float)Math.toRadians(15.0), 0.0F, 0.0F);
        this.animator.move(this.right_leg, 0.0F, 0.0F, -4.0F);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.resetKeyframe(10);
        this.animator.setAnimation(CoralGolemServant.CORAL_GOLEM_LEFT_SMASH);
        this.animator.startKeyframe(10);
        this.animator.rotate(this.lower_body, (float)Math.toRadians(-7.5), 0.0F, 0.0F);
        this.animator.rotate(this.upper_body, (float)Math.toRadians(-17.5), (float)Math.toRadians(-10.0), (float)Math.toRadians(-5.0));
        this.animator.rotate(this.helmet, (float)Math.toRadians(12.5), (float)Math.toRadians(5.0), (float)Math.toRadians(-2.5));
        this.animator.move(this.right_arm, -1.0F, 3.0F, -2.0F);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(10.0), (float)Math.toRadians(7.5), (float)Math.toRadians(5.0));
        this.animator.rotate(this.right_fist, (float)Math.toRadians(7.5), 0.0F, 0.0F);
        this.animator.move(this.left_arm, -1.0F, 0.0F, 3.0F);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-142.5), (float)Math.toRadians(-5.0), (float)Math.toRadians(5.0));
        this.animator.rotate(this.left_fist, (float)Math.toRadians(-25.0), 0.0F, 0.0F);
        this.animator.move(this.right_leg, 0.0F, 0.0F, -4.0F);
        this.animator.move(this.left_leg, 0.0F, 0.0F, 1.0F);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(5);
        this.animator.startKeyframe(1);
        this.animator.rotate(this.lower_body, (float)Math.toRadians(5.0), (float)Math.toRadians(5.0), 0.0F);
        this.animator.rotate(this.upper_body, (float)Math.toRadians(-15.0), (float)Math.toRadians(10.0), (float)Math.toRadians(2.5));
        this.animator.rotate(this.helmet, (float)Math.toRadians(2.5), (float)Math.toRadians(5.0), (float)Math.toRadians(-2.5));
        this.animator.move(this.right_arm, 0.0F, 3.0F, 0.0F);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(25.0), (float)Math.toRadians(-10.0), (float)Math.toRadians(-2.5));
        this.animator.rotate(this.right_fist, (float)Math.toRadians(-15.0), 0.0F, 0.0F);
        this.animator.move(this.left_arm, -2.0F, 2.0F, -1.0F);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-10.0), (float)Math.toRadians(2.5), (float)Math.toRadians(12.5));
        this.animator.rotate(this.left_fist, (float)Math.toRadians(-25.0), 0.0F, 0.0F);
        this.animator.move(this.left_leg, 0.0F, 0.0F, -3.0F);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.resetKeyframe(10);
        this.animator.setAnimation(CoralGolemServant.CORAL_GOLEM_RIGHT_SMASH);
        this.animator.startKeyframe(10);
        this.animator.rotate(this.lower_body, (float)Math.toRadians(-7.5), 0.0F, 0.0F);
        this.animator.rotate(this.upper_body, (float)Math.toRadians(-17.5), (float)Math.toRadians(10.0), (float)Math.toRadians(5.0));
        this.animator.rotate(this.helmet, (float)Math.toRadians(12.5), (float)Math.toRadians(-5.0), (float)Math.toRadians(2.5));
        this.animator.move(this.left_arm, 0.0F, 3.0F, -2.0F);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(10.0), (float)Math.toRadians(-7.5), (float)Math.toRadians(-5.0));
        this.animator.rotate(this.left_fist, (float)Math.toRadians(7.5), 0.0F, 0.0F);
        this.animator.move(this.right_arm, 1.0F, 0.0F, 3.0F);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-142.5), (float)Math.toRadians(5.0), (float)Math.toRadians(-5.0));
        this.animator.rotate(this.right_fist, (float)Math.toRadians(-25.0), 0.0F, 0.0F);
        this.animator.move(this.left_leg, 0.0F, 0.0F, -4.0F);
        this.animator.move(this.right_leg, 0.0F, 0.0F, 1.0F);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(5);
        this.animator.startKeyframe(1);
        this.animator.rotate(this.lower_body, (float)Math.toRadians(5.0), (float)Math.toRadians(-5.0), 0.0F);
        this.animator.rotate(this.upper_body, (float)Math.toRadians(-15.0), (float)Math.toRadians(-10.0), (float)Math.toRadians(-2.5));
        this.animator.rotate(this.helmet, (float)Math.toRadians(2.5), (float)Math.toRadians(-5.0), (float)Math.toRadians(2.5));
        this.animator.move(this.left_arm, 0.0F, 3.0F, 0.0F);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(25.0), (float)Math.toRadians(10.0), (float)Math.toRadians(2.5));
        this.animator.rotate(this.left_fist, (float)Math.toRadians(-15.0), 0.0F, 0.0F);
        this.animator.move(this.right_arm, 2.0F, 2.0F, -1.0F);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-10.0), (float)Math.toRadians(-2.5), (float)Math.toRadians(-12.5));
        this.animator.rotate(this.right_fist, (float)Math.toRadians(-25.0), 0.0F, 0.0F);
        this.animator.move(this.right_leg, 0.0F, 0.0F, -3.0F);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.resetKeyframe(10);
    }

    public void setupAnim(CoralGolemServant entityIn, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        this.animate(entityIn, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch);
        float walkSpeed = 0.5F;
        float walkDegree = 0.5F;
        float partialTick = Minecraft.getInstance().getFrameTime();
        float swim = entityIn.getSwimAmount(partialTick);
        float swimSpeed = 0.25F;
        float swimDegree = 0.5F;
        float swimAmount = limbSwingAmount * swim;
        this.faceTarget(netHeadYaw, headPitch, 1.0F, new AdvancedModelBox[]{this.head});
        this.walk(this.left_leg, walkSpeed, walkDegree * 1.2F, true, 0.0F, 0.0F, limbSwing, limbSwingAmount);
        this.flap(this.root, walkSpeed, walkDegree * 0.2F, false, 0.0F, 0.0F, limbSwing, limbSwingAmount);
        this.walk(this.right_leg, walkSpeed, walkDegree * 1.2F, false, 0.0F, 0.0F, limbSwing, limbSwingAmount);
        this.walk(this.left_arm, walkSpeed, walkDegree * 1.2F, false, 0.0F, 0.0F, limbSwing, limbSwingAmount);
        this.walk(this.right_arm, walkSpeed, walkDegree * 1.2F, true, 0.0F, 0.0F, limbSwing, limbSwingAmount);
        this.progressRotationPrev(this.root, swim, 0.0F, 0.0F, (float)Math.toRadians(-10.0), 1.0F);
        this.progressRotationPrev(this.lower_body, swim, (float)Math.toRadians(17.5), 0.0F, 0.0F, 1.0F);
        this.progressRotationPrev(this.head, swim, (float)Math.toRadians(-22.5), 0.0F, 0.0F, 1.0F);
        this.progressRotationPrev(this.right_arm, swim, (float)Math.toRadians(35.0), 0.0F, (float)Math.toRadians(50.0), 1.0F);
        this.progressRotationPrev(this.left_arm, swim, (float)Math.toRadians(35.0), 0.0F, (float)Math.toRadians(-50.0), 1.0F);
        this.progressRotationPrev(this.right_leg, swim, (float)Math.toRadians(90.0), 0.0F, 0.0F, 1.0F);
        this.progressRotationPrev(this.left_leg, swim, (float)Math.toRadians(117.5), 0.0F, 0.0F, 1.0F);
        this.flap(this.root, swimSpeed, swimDegree * 1.0F, true, 0.0F, 0.0F, limbSwing, swimAmount);
        this.flap(this.left_arm, swimSpeed, swimDegree * 2.75F, true, -0.5F, 1.5F, limbSwing, swimAmount);
        this.flap(this.right_arm, swimSpeed, swimDegree * 2.75F, false, -0.5F, 1.5F, limbSwing, swimAmount);
        this.walk(this.right_leg, swimSpeed * 1.5F, swimDegree * 1.0F, true, 2.0F, 0.0F, limbSwing, swimAmount);
        this.walk(this.left_leg, swimSpeed * 1.5F, swimDegree * 1.0F, false, 2.0F, 0.0F, limbSwing, swimAmount);
    }

    public Iterable<AdvancedModelBox> getAllParts() {
        return ImmutableList.of(this.root, this.lower_body, this.upper_body, this.helmet, this.chest, this.table_coral, this.blue_table_coral, this.red_table_coral, this.right_arm, this.right_fist, this.right_coral, this.left_arm, new AdvancedModelBox[]{this.left_fist, this.left_coral, this.coral_shoulder, this.head, this.right_leg, this.left_leg});
    }

    public Iterable<BasicModelPart> parts() {
        return ImmutableList.of(this.root);
    }

    public void setRotationAngle(AdvancedModelBox AdvancedModelBox, float x, float y, float z) {
        AdvancedModelBox.rotateAngleX = x;
        AdvancedModelBox.rotateAngleY = y;
        AdvancedModelBox.rotateAngleZ = z;
    }
}
