package com.Polarice3.goety_cataclysm.client.render.model;

import com.Polarice3.goety_cataclysm.common.entities.ally.golem.EnderGolemServant;
import com.github.L_Ender.lionfishapi.client.model.Animations.ModelAnimator;
import com.github.L_Ender.lionfishapi.client.model.tools.AdvancedEntityModel;
import com.github.L_Ender.lionfishapi.client.model.tools.AdvancedModelBox;
import com.github.L_Ender.lionfishapi.client.model.tools.BasicModelPart;
import com.google.common.collect.ImmutableList;
import net.minecraft.client.Minecraft;

public class EnderGolemServantModel extends AdvancedEntityModel<EnderGolemServant> {
    private final AdvancedModelBox root;
    private final AdvancedModelBox lowerbody;
    private final AdvancedModelBox upperbody;
    private final AdvancedModelBox voidstone;
    private final AdvancedModelBox right_arm;
    private final AdvancedModelBox right_arm2;
    private final AdvancedModelBox right_finger;
    private final AdvancedModelBox left_arm;
    private final AdvancedModelBox left_arm2;
    private final AdvancedModelBox left_finger;
    private final AdvancedModelBox head;
    private final AdvancedModelBox right_leg;
    private final AdvancedModelBox left_leg;
    private ModelAnimator animator;

    public EnderGolemServantModel() {
        this.texWidth = 256;
        this.texHeight = 256;
        this.root = new AdvancedModelBox(this);
        this.root.setRotationPoint(0.0F, 24.0F, 0.0F);
        this.lowerbody = new AdvancedModelBox(this);
        this.lowerbody.setRotationPoint(0.0F, -20.0F, 0.0F);
        this.root.addChild(this.lowerbody);
        this.lowerbody.setTextureOffset(64, 52).addBox(-11.0F, -8.0F, -7.0F, 22.0F, 8.0F, 14.0F, 0.0F, false);
        this.upperbody = new AdvancedModelBox(this);
        this.upperbody.setRotationPoint(0.0F, -7.0F, 0.0F);
        this.lowerbody.addChild(this.upperbody);
        this.upperbody.setTextureOffset(0, 0).addBox(-20.0F, -32.0F, -10.0F, 40.0F, 32.0F, 20.0F, 0.0F, false);
        this.voidstone = new AdvancedModelBox(this);
        this.voidstone.setRotationPoint(0.0F, -12.0F, 9.0F);
        this.upperbody.addChild(this.voidstone);
        this.voidstone.setTextureOffset(0, 52).addBox(-8.0F, -8.0F, -8.0F, 16.0F, 16.0F, 16.0F, 0.0F, false);
        this.right_arm = new AdvancedModelBox(this);
        this.right_arm.setRotationPoint(-20.0F, -25.0F, 0.0F);
        this.upperbody.addChild(this.right_arm);
        this.right_arm.setTextureOffset(52, 74).addBox(-14.0F, -6.0F, -6.0F, 14.0F, 24.0F, 12.0F, 0.0F, false);
        this.right_arm2 = new AdvancedModelBox(this);
        this.right_arm2.setRotationPoint(-10.5F, 18.0F, 0.0F);
        this.right_arm.addChild(this.right_arm2);
        this.right_arm2.setTextureOffset(92, 98).addBox(-5.5F, 0.0F, -6.0F, 11.0F, 22.0F, 12.0F, 0.0F, false);
        this.right_arm2.setTextureOffset(0, 52).addBox(1.5F, 22.0F, -3.0F, 3.0F, 7.0F, 5.0F, 0.0F, false);
        this.right_finger = new AdvancedModelBox(this);
        this.right_finger.setRotationPoint(-3.5F, 22.0F, 0.0F);
        this.right_arm2.addChild(this.right_finger);
        this.right_finger.setTextureOffset(0, 0).addBox(-1.0F, 0.0F, -5.5F, 3.0F, 8.0F, 5.0F, 0.0F, false);
        this.right_finger.setTextureOffset(0, 0).addBox(-1.0F, 0.0F, 0.5F, 3.0F, 8.0F, 5.0F, 0.0F, false);
        this.left_arm = new AdvancedModelBox(this);
        this.left_arm.setRotationPoint(20.0F, -25.0F, 0.0F);
        this.upperbody.addChild(this.left_arm);
        this.left_arm.setTextureOffset(52, 74).addBox(0.0F, -6.0F, -6.0F, 14.0F, 24.0F, 12.0F, 0.0F, true);
        this.left_arm2 = new AdvancedModelBox(this);
        this.left_arm2.setRotationPoint(10.5F, 18.0F, 0.0F);
        this.left_arm.addChild(this.left_arm2);
        this.left_arm2.setTextureOffset(92, 98).addBox(-5.5F, 0.0F, -6.0F, 11.0F, 22.0F, 12.0F, 0.0F, true);
        this.left_arm2.setTextureOffset(0, 52).addBox(-4.5F, 22.0F, -3.0F, 3.0F, 7.0F, 5.0F, 0.0F, true);
        this.left_finger = new AdvancedModelBox(this);
        this.left_finger.setRotationPoint(3.5F, 22.0F, 0.0F);
        this.left_arm2.addChild(this.left_finger);
        this.left_finger.setTextureOffset(0, 0).addBox(-2.0F, 0.0F, -5.5F, 3.0F, 8.0F, 5.0F, 0.0F, true);
        this.left_finger.setTextureOffset(0, 0).addBox(-2.0F, 0.0F, 0.5F, 3.0F, 8.0F, 5.0F, 0.0F, true);
        this.head = new AdvancedModelBox(this);
        this.head.setRotationPoint(0.0F, -25.0F, -10.0F);
        this.upperbody.addChild(this.head);
        this.head.setTextureOffset(0, 98).addBox(-8.0F, -8.0F, -12.0F, 16.0F, 16.0F, 12.0F, 0.0F, false);
        this.right_leg = new AdvancedModelBox(this);
        this.right_leg.setRotationPoint(-11.0F, -20.0F, 0.0F);
        this.root.addChild(this.right_leg);
        this.right_leg.setTextureOffset(44, 114).addBox(-8.0F, 0.0F, -6.0F, 12.0F, 20.0F, 12.0F, 0.0F, false);
        this.left_leg = new AdvancedModelBox(this);
        this.left_leg.setRotationPoint(11.0F, -20.0F, 0.0F);
        this.root.addChild(this.left_leg);
        this.left_leg.setTextureOffset(44, 114).addBox(-4.0F, 0.0F, -6.0F, 12.0F, 20.0F, 12.0F, 0.0F, true);
        this.animator = ModelAnimator.create();
        this.updateDefaultPose();
    }

    public void animate(EnderGolemServant entity, float f, float f1, float f2, float f3, float f4) {
        this.resetToDefaultPose();
        this.animator.update(entity);
        this.animator.setAnimation(EnderGolemServant.ANIMATION_ATTACK1);
        this.animator.startKeyframe(10);
        this.animator.rotate(this.upperbody, 0.0F, (float)Math.toRadians(50.0), 0.0F);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(40.0), (float)Math.toRadians(20.0), 0.0F);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-80.0), 0.0F, 0.0F);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(20.0), 0.0F, (float)Math.toRadians(-10.0));
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
        this.animator.endKeyframe();
        this.animator.startKeyframe(5);
        this.animator.rotate(this.lowerbody, 0.0F, (float)Math.toRadians(-20.0), 0.0F);
        this.animator.rotate(this.upperbody, 0.0F, (float)Math.toRadians(-40.0), 0.0F);
        this.animator.rotate(this.head, 0.0F, (float)Math.toRadians(30.0), 0.0F);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-20.0), (float)Math.toRadians(20.0), (float)Math.toRadians(20.0));
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-20.0), 0.0F, 0.0F);
        this.animator.rotate(this.right_finger, 0.0F, 0.0F, (float)Math.toRadians(-40.0));
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-40.0), 0.0F, 0.0F);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(5);
        this.animator.resetKeyframe(5);
        this.animator.setAnimation(EnderGolemServant.ANIMATION_ATTACK2);
        this.animator.startKeyframe(10);
        this.animator.rotate(this.upperbody, 0.0F, (float)Math.toRadians(-50.0), 0.0F);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(40.0), (float)Math.toRadians(-20.0), 0.0F);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-80.0), 0.0F, 0.0F);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(20.0), 0.0F, (float)Math.toRadians(10.0));
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
        this.animator.endKeyframe();
        this.animator.startKeyframe(5);
        this.animator.rotate(this.lowerbody, 0.0F, (float)Math.toRadians(20.0), 0.0F);
        this.animator.rotate(this.upperbody, 0.0F, (float)Math.toRadians(40.0), 0.0F);
        this.animator.rotate(this.head, 0.0F, (float)Math.toRadians(-30.0), 0.0F);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-20.0), (float)Math.toRadians(-20.0), (float)Math.toRadians(-20.0));
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-20.0), 0.0F, 0.0F);
        this.animator.rotate(this.left_finger, 0.0F, 0.0F, (float)Math.toRadians(40.0));
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-40.0), 0.0F, 0.0F);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(5);
        this.animator.resetKeyframe(5);
        this.animator.setAnimation(EnderGolemServant.ANIMATION_EARTHQUAKE);
        this.animator.startKeyframe(10);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(-15.0), 0.0F, 0.0F);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(-15.0), 0.0F, 0.0F);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-160.0), (float)Math.toRadians(20.0), (float)Math.toRadians(-10.0));
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-160.0), (float)Math.toRadians(-20.0), (float)Math.toRadians(10.0));
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-20.0), 0.0F, 0.0F);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-20.0), 0.0F, 0.0F);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(5);
        this.animator.startKeyframe(5);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(30.0), 0.0F, 0.0F);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(40.0), 0.0F, 0.0F);
        this.animator.rotate(this.head, (float)Math.toRadians(-60.0), 0.0F, 0.0F);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-100.0), (float)Math.toRadians(20.0), (float)Math.toRadians(-10.0));
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-100.0), (float)Math.toRadians(-20.0), (float)Math.toRadians(10.0));
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
        this.animator.rotate(this.left_finger, 0.0F, 0.0F, (float)Math.toRadians(40.0));
        this.animator.rotate(this.right_finger, 0.0F, 0.0F, (float)Math.toRadians(-40.0));
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(5);
        this.animator.resetKeyframe(10);
        this.animator.setAnimation(EnderGolemServant.VOID_RUNE_ATTACK);
        this.animator.startKeyframe(13);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(-12.5), 0.0F, 0.0F);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(-10.0), 0.0F, 0.0F);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-170.0), 0.0F, 0.0F);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-180.0), 0.0F, 0.0F);
        this.animator.rotate(this.right_finger, 0.0F, 0.0F, (float)Math.toRadians(-17.5));
        this.animator.rotate(this.left_finger, 0.0F, 0.0F, (float)Math.toRadians(17.5));
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(5);
        this.animator.startKeyframe(5);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(45.0), 0.0F, 0.0F);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(17.5), 0.0F, 0.0F);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-50.0), 0.0F, 0.0F);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-50.0), 0.0F, 0.0F);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-60.0), 0.0F, 0.0F);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-60.0), 0.0F, 0.0F);
        this.animator.rotate(this.right_finger, 0.0F, 0.0F, (float)Math.toRadians(-17.5));
        this.animator.rotate(this.left_finger, 0.0F, 0.0F, (float)Math.toRadians(17.5));
        this.animator.endKeyframe();
        this.animator.startKeyframe(15);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(45.0), 0.0F, 0.0F);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(17.5), 0.0F, 0.0F);
        this.animator.move(this.voidstone, 0.0F, 0.0F, 8.0F);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-50.0), 0.0F, 0.0F);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-50.0), 0.0F, 0.0F);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-60.0), 0.0F, 0.0F);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-60.0), 0.0F, 0.0F);
        this.animator.rotate(this.right_finger, 0.0F, 0.0F, (float)Math.toRadians(-17.5));
        this.animator.rotate(this.left_finger, 0.0F, 0.0F, (float)Math.toRadians(17.5));
        this.animator.endKeyframe();
        this.animator.startKeyframe(10);
        this.animator.rotate(this.lowerbody, (float)Math.toRadians(45.0), 0.0F, 0.0F);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(17.5), 0.0F, 0.0F);
        this.animator.move(this.voidstone, 0.0F, 0.0F, -1.0F);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-50.0), 0.0F, 0.0F);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-50.0), 0.0F, 0.0F);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-60.0), 0.0F, 0.0F);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-60.0), 0.0F, 0.0F);
        this.animator.rotate(this.right_finger, 0.0F, 0.0F, (float)Math.toRadians(-17.5));
        this.animator.rotate(this.left_finger, 0.0F, 0.0F, (float)Math.toRadians(17.5));
        this.animator.endKeyframe();
        this.animator.startKeyframe(10);
        this.animator.rotate(this.upperbody, (float)Math.toRadians(-2.5), 0.0F, 0.0F);
        this.animator.move(this.voidstone, 0.0F, 0.0F, -1.0F);
        this.animator.rotate(this.right_arm, (float)Math.toRadians(-62.5), 0.0F, 0.0F);
        this.animator.rotate(this.left_arm, (float)Math.toRadians(-62.5), 0.0F, 0.0F);
        this.animator.rotate(this.right_arm2, (float)Math.toRadians(-60.0), 0.0F, 0.0F);
        this.animator.rotate(this.left_arm2, (float)Math.toRadians(-60.0), 0.0F, 0.0F);
        this.animator.rotate(this.right_finger, 0.0F, 0.0F, (float)Math.toRadians(-17.5));
        this.animator.rotate(this.left_finger, 0.0F, 0.0F, (float)Math.toRadians(-17.5));
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.resetKeyframe(15);
        this.animator.setAnimation(EnderGolemServant.ENDER_GOLEM_DEATH);
        if (entity.getIsAwaken()) {
            this.animator.startKeyframe(10);
            this.animator.rotate(this.right_leg, (float)Math.toRadians(90.0), 0.0F, 0.0F);
            this.animator.rotate(this.left_leg, (float)Math.toRadians(90.0), 0.0F, 0.0F);
            this.animator.rotate(this.right_arm2, (float)Math.toRadians(55.0), 0.0F, 0.0F);
            this.animator.rotate(this.left_arm2, (float)Math.toRadians(55.0), 0.0F, 0.0F);
            this.animator.move(this.lowerbody, 0.0F, 14.0F, 0.0F);
            this.animator.move(this.right_leg, 0.0F, 14.0F, 0.0F);
            this.animator.move(this.left_leg, 0.0F, 14.0F, 0.0F);
            this.animator.endKeyframe();
            this.animator.setStaticKeyframe(5);
            this.animator.startKeyframe(20);
            this.animator.rotate(this.upperbody, (float)Math.toRadians(-12.5), 0.0F, 0.0F);
            this.animator.rotate(this.right_leg, (float)Math.toRadians(90.0), 0.0F, 0.0F);
            this.animator.rotate(this.left_leg, (float)Math.toRadians(90.0), 0.0F, 0.0F);
            this.animator.rotate(this.right_arm, (float)Math.toRadians(15.0), 0.0F, 0.0F);
            this.animator.rotate(this.left_arm, (float)Math.toRadians(15.0), 0.0F, 0.0F);
            this.animator.rotate(this.right_arm2, (float)Math.toRadians(55.0), 0.0F, 0.0F);
            this.animator.rotate(this.left_arm2, (float)Math.toRadians(55.0), 0.0F, 0.0F);
            this.animator.move(this.lowerbody, 0.0F, 14.0F, 0.0F);
            this.animator.move(this.right_leg, 0.0F, 14.0F, 0.0F);
            this.animator.move(this.left_leg, 0.0F, 14.0F, 0.0F);
            this.animator.endKeyframe();
            this.animator.setStaticKeyframe(5);
            this.animator.startKeyframe(5);
            this.animator.rotate(this.lowerbody, (float)Math.toRadians(62.5), 0.0F, 0.0F);
            this.animator.rotate(this.right_leg, (float)Math.toRadians(90.0), 0.0F, 0.0F);
            this.animator.rotate(this.left_leg, (float)Math.toRadians(90.0), 0.0F, 0.0F);
            this.animator.rotate(this.right_arm2, (float)Math.toRadians(10.0), 0.0F, 0.0F);
            this.animator.rotate(this.left_arm2, (float)Math.toRadians(10.0), 0.0F, 0.0F);
            this.animator.move(this.lowerbody, 0.0F, 14.0F, 0.0F);
            this.animator.move(this.right_leg, 0.0F, 14.0F, 0.0F);
            this.animator.move(this.left_leg, 0.0F, 14.0F, 0.0F);
            this.animator.endKeyframe();
            this.animator.setStaticKeyframe(50);
        } else {
            this.animator.startKeyframe(10);
            this.animator.rotate(this.lowerbody, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
            this.animator.rotate(this.upperbody, (float)Math.toRadians(-17.5), 0.0F, 0.0F);
            this.animator.rotate(this.right_leg, (float)Math.toRadians(90.0), 0.0F, 0.0F);
            this.animator.rotate(this.left_leg, (float)Math.toRadians(90.0), 0.0F, 0.0F);
            this.animator.rotate(this.right_arm, (float)Math.toRadians(47.5), 0.0F, 0.0F);
            this.animator.rotate(this.left_arm, (float)Math.toRadians(47.5), 0.0F, 0.0F);
            this.animator.rotate(this.right_arm2, (float)Math.toRadians(85.0), 0.0F, 0.0F);
            this.animator.rotate(this.left_arm2, (float)Math.toRadians(85.0), 0.0F, 0.0F);
            this.animator.rotate(this.right_finger, 0.0F, 0.0F, (float)Math.toRadians(35.0));
            this.animator.rotate(this.left_finger, 0.0F, 0.0F, (float)Math.toRadians(35.0));
            this.animator.rotate(this.head, (float)Math.toRadians(-15.0), 0.0F, 0.0F);
            this.animator.move(this.lowerbody, 0.0F, 14.0F, 0.0F);
            this.animator.move(this.right_leg, 0.0F, 14.0F, 0.0F);
            this.animator.move(this.left_leg, 0.0F, 14.0F, 0.0F);
            this.animator.endKeyframe();
            this.animator.setStaticKeyframe(5);
            this.animator.startKeyframe(20);
            this.animator.rotate(this.lowerbody, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
            this.animator.rotate(this.upperbody, (float)Math.toRadians(-30.0), 0.0F, 0.0F);
            this.animator.rotate(this.right_leg, (float)Math.toRadians(90.0), 0.0F, 0.0F);
            this.animator.rotate(this.left_leg, (float)Math.toRadians(90.0), 0.0F, 0.0F);
            this.animator.rotate(this.right_arm, (float)Math.toRadians(62.5), 0.0F, 0.0F);
            this.animator.rotate(this.left_arm, (float)Math.toRadians(62.5), 0.0F, 0.0F);
            this.animator.rotate(this.right_arm2, (float)Math.toRadians(85.0), 0.0F, 0.0F);
            this.animator.rotate(this.left_arm2, (float)Math.toRadians(85.0), 0.0F, 0.0F);
            this.animator.rotate(this.right_finger, 0.0F, 0.0F, (float)Math.toRadians(35.0));
            this.animator.rotate(this.left_finger, 0.0F, 0.0F, (float)Math.toRadians(35.0));
            this.animator.rotate(this.head, (float)Math.toRadians(-15.0), 0.0F, 0.0F);
            this.animator.move(this.lowerbody, 0.0F, 14.0F, 0.0F);
            this.animator.move(this.right_leg, 0.0F, 14.0F, 0.0F);
            this.animator.move(this.left_leg, 0.0F, 14.0F, 0.0F);
            this.animator.endKeyframe();
            this.animator.setStaticKeyframe(5);
            this.animator.startKeyframe(5);
            this.animator.rotate(this.lowerbody, (float)Math.toRadians(32.5), 0.0F, 0.0F);
            this.animator.rotate(this.upperbody, (float)Math.toRadians(-17.5), 0.0F, 0.0F);
            this.animator.rotate(this.right_leg, (float)Math.toRadians(90.0), 0.0F, 0.0F);
            this.animator.rotate(this.left_leg, (float)Math.toRadians(90.0), 0.0F, 0.0F);
            this.animator.rotate(this.right_arm, (float)Math.toRadians(47.5), 0.0F, 0.0F);
            this.animator.rotate(this.left_arm, (float)Math.toRadians(47.5), 0.0F, 0.0F);
            this.animator.rotate(this.right_arm2, (float)Math.toRadians(40.0), 0.0F, 0.0F);
            this.animator.rotate(this.left_arm2, (float)Math.toRadians(40.0), 0.0F, 0.0F);
            this.animator.rotate(this.right_finger, 0.0F, 0.0F, (float)Math.toRadians(35.0));
            this.animator.rotate(this.left_finger, 0.0F, 0.0F, (float)Math.toRadians(35.0));
            this.animator.rotate(this.head, (float)Math.toRadians(-15.0), 0.0F, 0.0F);
            this.animator.move(this.lowerbody, 0.0F, 14.0F, 0.0F);
            this.animator.move(this.right_leg, 0.0F, 14.0F, 0.0F);
            this.animator.move(this.left_leg, 0.0F, 14.0F, 0.0F);
            this.animator.endKeyframe();
            this.animator.setStaticKeyframe(50);
        }

    }

    public void setupAnim(EnderGolemServant entityIn, float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch) {
        this.animate(entityIn, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch);
        float walkSpeed = 0.5F;
        float walkDegree = 0.5F;
        this.faceTarget(netHeadYaw, headPitch, 1.0F, this.head);
        this.walk(this.left_leg, walkSpeed, walkDegree * 1.2F, true, 0.0F, 0.0F, limbSwing, limbSwingAmount);
        this.flap(this.root, walkSpeed, walkDegree * 0.2F, false, 0.0F, 0.0F, limbSwing, limbSwingAmount);
        this.walk(this.right_leg, walkSpeed, walkDegree * 1.2F, false, 0.0F, 0.0F, limbSwing, limbSwingAmount);
        this.walk(this.left_arm, walkSpeed, walkDegree * 1.2F, false, 0.0F, 0.0F, limbSwing, limbSwingAmount);
        this.walk(this.right_arm, walkSpeed, walkDegree * 1.2F, true, 0.0F, 0.0F, limbSwing, limbSwingAmount);
        float partialTick = Minecraft.getInstance().getFrameTime();
        float deactivateProgress = entityIn.prevDeactivateProgress + (entityIn.deactivateProgress - entityIn.prevDeactivateProgress) * partialTick;
        this.progressRotationPrev(this.lowerbody, deactivateProgress, (float)Math.toRadians(30.0), 0.0F, 0.0F, 30.0F);
        this.progressRotationPrev(this.upperbody, deactivateProgress, (float)Math.toRadians(17.5), 0.0F, 0.0F, 30.0F);
        this.progressRotationPrev(this.right_arm, deactivateProgress, (float)Math.toRadians(-47.5), 0.0F, 0.0F, 30.0F);
        this.progressRotationPrev(this.left_arm, deactivateProgress, (float)Math.toRadians(-47.5), 0.0F, 0.0F, 30.0F);
        this.progressRotationPrev(this.right_arm2, deactivateProgress, (float)Math.toRadians(-30.0), 0.0F, 0.0F, 30.0F);
        this.progressRotationPrev(this.left_arm2, deactivateProgress, (float)Math.toRadians(-30.0), 0.0F, 0.0F, 30.0F);
        this.progressRotationPrev(this.right_finger, deactivateProgress, 0.0F, 0.0F, (float)Math.toRadians(-35.0), 30.0F);
        this.progressRotationPrev(this.left_finger, deactivateProgress, 0.0F, 0.0F, (float)Math.toRadians(35.0), 30.0F);
        this.progressRotationPrev(this.head, deactivateProgress, (float)Math.toRadians(15.0), 0.0F, 0.0F, 30.0F);
    }

    public Iterable<AdvancedModelBox> getAllParts() {
        return ImmutableList.of(this.root, this.left_arm, this.right_arm, this.left_arm2, this.right_arm2, this.left_finger, this.right_finger, this.left_leg, this.right_leg, this.head, this.lowerbody, this.upperbody, new AdvancedModelBox[]{this.voidstone});
    }

    public Iterable<BasicModelPart> parts() {
        return ImmutableList.of(this.root);
    }

    public void setRotationAngle(AdvancedModelBox AdvancedModelBox, float x, float y, float z) {
        AdvancedModelBox.rotateAngleX = x;
        AdvancedModelBox.rotateAngleY = y;
        AdvancedModelBox.rotateAngleZ = z;
    }
}
