modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
[[mods]]
modId="goety_cataclysm"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/Polarice3/Goety_Cataclysm"
logoFile="GCLogo.png"
credits="L_Ender for making L_Ender's Cataclysm, Lionfish API."
authors="Polarice3"
description='''
Compat mod between Goety and L_Ender's Cataclysm
'''
[[dependencies.goety_cataclysm]]
modId="forge"
mandatory=true
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.goety_cataclysm]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.goety_cataclysm]]
modId="goety"
mandatory=true
versionRange="[2.5.33.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.goety_cataclysm]]
modId="cataclysm"
mandatory=true
versionRange="[2.65,)"
ordering="NONE"
side="BOTH"
